In [1]:
import sys
from pathlib import Path
NOTEBOOKS = Path.cwd()                          # <-- Edit as needed
NN_POSTPROCESSING = NOTEBOOKS.parents[0]        # <-- Edit as needed
BAMBOO_SETUP = NOTEBOOKS.parents[3]             # <-- Edit as needed
Z_OUTPUT_eos = Path('/Users/antonett/Documents/HH Analysis/Z_OUTPUT_eos')   # <-- Edit as needed
sys.path.append(str((BAMBOO_SETUP/'src').resolve()))
import pandas as pd
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.width', 1000)  # Set a larger width to fit the editor window
# pd.set_option('display.max_colwidth', None)  # Allow columns to be fully displayed
%load_ext autoreload

In [2]:
from post_processing.NN.DataHandler import DataHandler
import logging
datahandler = DataHandler(
    workdir=Z_OUTPUT_eos/'2022_even_1013/Reco',
    tree_name='SL_res_2b_x',
    total_inputs= NN_POSTPROCESSING / 'input/vars40_new.txt',
    log_level=logging.DEBUG
)
# total_df = datahandler.start()
total_df_unprep = datahandler.load_data()
total_df_unprep = datahandler.fix_column_names_mismatch(total_df_unprep)
datahandler.data_inspection(total_df_unprep)
# datahandler.data_summary(total_df_unprep)
df = datahandler.preprocess_data(total_df_unprep)
datahandler.data_inspection(df)

In module 'Darwin':
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/libkern/arm/OSByteOrder.h:14:1: error: '_OSSwapInt16' has different definitions in different modules; definition in module 'Darwin.libkern.OSByteOrder' first difference is return type is 'uint16_t' (aka 'unsigned short')
uint16_t
^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/libkern/arm/_OSByteOrder.h:49:1: note: but in 'DarwinFoundation.OSByteOrder' found different return type '__uint16_t' (aka 'unsigned short')
__uint16_t
^~~~~~~~~~
In module 'Darwin':
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/libkern/arm/OSByteOrder.h:24:1: error: '_OSSwapInt32' has different definitions in different modules; definition in module 'Darwin.libkern.OSByteOrder' first difference is return type is 'uint32_t' (aka 'unsigned int')
uint32_t
^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/libkern/arm/_OSByteOrder.h:59:1: note: but in 'DarwinFoundation.OSByteOrder' found different return type '__uint32_t' (aka 'unsigned int')
__uint32_t
^~~~~~~~~~
In module 'Darwin':
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/libkern/arm/OSByteOrder.h:40:1: error: '_OSSwapInt64' has different definitions in different modules; definition in module 'Darwin.libkern.OSByteOrder' first difference is return type is 'uint64_t' (aka 'unsigned long long')
uint64_t
^~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/usr/include/libkern/arm/_OSByteOrder.h:75:1: note: but in 'DarwinFoundation.OSByteOrder' found different return type '__uint64_t' (aka 'unsigned long long')
__uint64_t
^~~~~~~~~~

Loading data...
	File: DY_dl_mll_50_1J
	File: DY_dl_mll_50_0J
	File: DY_dl_mll_10to50
	File: DY_dl_mll_50_2J
	File: bbWW_dl
	File: bbWW_sl
	File: bbtautau
	File: ZZ
	File: WW
	File: WZ
	File: Wjets_2J
	File: Wjets_0J
	File: Wjets_1J
	File: tbarWplus_sl
	File: tWminus_sl
	File: tWminus_dl
	File: tbarWplus_dl
	File: TTbar_dl
	File: TTbar_sl
	Total_df:
             event     genWeight  nAK4  nAK4_btag     lep0_pt  lep0_eta  lep0_phi  ak4_jet0_pt  ak4_jet0_eta  ak4_jet0_phi  ak4_jet1_pt  ak4_jet1_eta  ak4_jet1_phi  ak4_jet2_pt  ak4_jet2_eta  ak4_jet2_phi  ak4_btag0_pt  ak4_btag0_eta  ak4_btag0_phi  ak4_btag1_pt  ak4_btag1_eta  ak4_btag1_phi      met_pt   met_phi   bjets_mbb  bjets_dPhi  bjets_dEta  bjets_dR  bjets_pt_bb  trijet_mInv   trijet_pt  trijet_pt_rat     blnu_mT     blnu_pt  trijet_bijet_dR  trijet_bijet_dPhi  bjet_bijet_dR  bjet_bijet_dPhi     all_pt     all_mInv  all_jets_HT         mjj          File  Process
387977          18      3.805950     4          2   89.622681  1.105957 -2.818848     172.5000      1.684570      0.624268     111.3750      1.175537     -1.235596     70.37500      0.964478      1.242432     172.50000       1.684570       0.624268     70.375000       0.964478       1.242432  116.074379 -2.936035  111.787468   -0.618164   -0.720093  0.949031   233.442108   275.532318  173.572144       0.559403  315.133392  176.526657         1.441196          -1.164057       2.027832        -1.962857  16.421644   697.857056   380.656250   41.493786  tbarWplus_dl       tW
2242769         22    337.046997     6          2   24.002106 -1.138565  0.132206     257.7500     -1.424072     -1.596436      94.8750      0.773926      1.199707     80.68750      1.667236      1.161865     257.75000      -1.424072      -1.596436     37.687500       1.211914       2.004883   65.833290 -1.534180  393.151337    2.681867    2.635986  3.760430   224.598801   114.136292  203.058990       0.952211  406.004089  320.889313         0.140181          -0.136447       0.824454        -0.822567  68.177055  1253.854858   567.843750   84.452141      TTbar_sl    ttbar
16422           32      0.033119     4          2   65.667160  1.346191  1.424072     192.0000     -0.145477     -1.602783     125.8125      0.816772      1.625244     50.75000     -0.764038     -0.813354     192.00000      -0.145477      -1.602783     50.750000      -0.764038      -0.813354   32.159973  2.111816  101.529617   -0.789429   -0.618561  1.002903   230.573227   414.172607   91.249809       0.259301  221.209976   62.258396         2.308760          -2.306782       3.132029        -2.781621  29.164007   644.934692   402.656250  122.545013       bbWW_sl  HH_bbWW
506544          36     81.103897     5          2   67.785812  0.904053  2.238770     156.3750     -1.606689     -1.665039      81.3125      1.302246      0.167908     61.37500     -0.245758     -1.079590      81.31250       1.302246       0.167908     57.187500      -0.330811      -2.950195  183.191925  1.643311  186.289108   -3.118103    1.633057  3.519864    24.178112   255.434219  224.622360       0.816994  389.353455  250.756989         0.255890           0.255418       1.784749         1.447144  49.349865  1012.982605   382.750000  158.995483      TTbar_dl    ttbar
16423           42      0.033119     5          2   36.858803  0.859253  0.675903     107.0625      1.249756      0.425049     100.6875      2.201172     -2.758301     69.25000      1.812744      0.727173     100.68750       2.201172      -2.758301     66.937500       1.660645      -1.680908   17.724852 -3.136719   96.761787    1.077393    0.540527  1.205382   144.923660   207.233261  143.871246       0.591454  212.537613   83.649582         0.651851           0.378334       2.229081         2.224385  44.142178   503.722900   371.109375   58.874733       bbWW_sl  HH_bbWW
...            ...           ...   ...        ...         ...       ...       ...          ...           ...           ...          ...           ...           ...          ...           ...           ...           ...            ...            ...           ...            ...            ...         ...       ...         ...         ...         ...       ...          ...          ...         ...            ...         ...         ...              ...                ...            ...              ...        ...          ...          ...         ...           ...      ...
37835    744899478  83745.546875     5          2   59.665302 -1.757812  0.698730     202.2500     -1.348389     -1.258057     107.3750     -0.597656      2.217285     48.09375     -1.324219     -1.848633      48.09375      -1.324219      -1.848633     32.312500      -1.132080       2.531738   58.569748  2.203125   65.643822    1.902814    0.192139  1.912490    48.415188   176.107742  216.791245       0.780658  200.408844  105.267464         0.133441           0.131878       0.686745         0.634457  38.376770   611.345886   417.390625  149.145844      Wjets_2J    WJets
37854    745108688  83745.546875     5          2  301.928619 -1.751953 -0.746704     119.6875     -0.370850      1.849609     113.3125     -1.625000     -2.983398     57.93750     -0.834839      2.156250     119.68750      -0.370850       1.849609     46.625000      -1.356445       1.432373   18.127060  2.047363   87.186371    0.417236   -0.985596  1.070273   163.408646   311.570160  211.947174       0.751502  400.758423  262.036163         0.602126           0.595978       1.697949         1.461237   8.570162   909.595398   386.593750  181.153564      Wjets_2J    WJets
37830    745244862  83745.546875     5          2   88.273689 -1.919922 -0.977783     232.3750     -1.377197      2.053711      98.1250      1.264648     -2.308594     59.65625      1.738037     -1.704834     232.37500      -1.377197       2.053711     44.593750       1.631836       0.933472   87.741211  0.211517  450.320038    1.120239    3.009033  3.210797   254.974060   824.478516  196.388107       0.503358  479.331268  162.759949         2.490620           1.445847       3.595784         2.146984  20.665476  1375.876343   473.250000   64.465408      Wjets_2J    WJets
37444    745282826 -83745.546875     5          2   30.953983 -1.701416  0.327148     159.2500     -1.088379      2.515137      97.7500      0.879395     -1.651611     62.59375      0.811646     -0.625122      50.34375       1.720947       1.928223     29.484375       0.299805       0.670044   49.198219 -0.842285   76.028702    1.258179   -1.421143  1.898067    65.702728   142.682297  133.232330       0.701858  276.986969   48.909901         0.224985          -0.208579       2.036801        -1.931365  18.687658   799.958252   399.421875   79.086487      Wjets_2J    WJets
37445    745344992  83745.546875     6          2   61.225887 -2.274536 -1.033905     128.7500     -2.158203      0.413940      70.8750      1.851562     -2.434570     48.65625     -0.527344      2.640137      48.65625      -0.527344       2.640137     25.406250      -0.862183       2.245117   38.443169 -1.881348   22.990396   -0.395020    0.334839  0.517839    72.765762   190.989853  155.340103       0.840315  230.701263   69.761620         0.172350          -0.160440       2.102293        -1.786786  85.606331  1093.098267   342.171875  140.113342      Wjets_2J    WJets

[2390092 rows x 44 columns]

Fixing column names mismatches if any...

Data inspection ...
	Duplicate events:
		Number of duplicate events found: 8747
	Negative genWeights:
		Number of events with negative genWeights: 14290
	Null Values (i.e NaN, None):
		No events with null values found.
	Additional checks on numeric features only:
		No events with inf values found.
		No events with values larger than abs(10000.0) found.

Preprocessing data ...
	Dropping exact duplicates if any ...
	Removing events with negative weights ...

Data inspection ...
	Duplicate events:
		No duplicate events found.
	Negative genWeights:
		No events with negative genWeights found.
	Null Values (i.e NaN, None):
		No events with null values found.
	Additional checks on numeric features only:
		No events with inf values found.
		No events with values larger than abs(10000.0) found.

# Set up your model config

In [18]:
from post_processing.NN.utils import ModelConfig
model_config = ModelConfig(
    name='multi_HH_ttbar_tW',
    type='multi',
    categorization={"HH": ["HH_bbWW"], "ttbar": ["ttbar"], "tW": ["tW"]},
    training_weight_sf={"HH_bbWW": 1.0, "ttbar": 8.0, "tW": 4.0},
    input_vars='All',
    architecture_in_yml=True,
    residual_network=True,
    hiddenlayers=[
        {"type": 'Dense', "units": 64, "activation": 'relu', "act_regularizer": {'l2': 1e-4}, "dropout_rate": 0.4},
        {"type": 'Dense', "units": 64, "activation": 'relu', "act_regularizer": {'l2': 1e-4}, "dropout_rate": 0.4},
        {"type": 'Dense', "units": 64, "activation": 'relu', "act_regularizer": {'l2': 1e-4}, "dropout_rate": 0.4}
    ],
    outputlayers=[
        {"type": 'Dense', "units": 3, "kernel_initializer": 'normal', "activation": 'softmax', "act_regularizer": {'l2': 1e-4}, "name": 'output'}
    ],
    compiler={"optimizer": 'adam', "lr": 0.001, "loss": 'categorical_crossentropy'},
    fit={"batch_size": 1024, "epochs": 35, "validation_split": 0.25}
)

In [32]:
%autoreload 2

# Run DNN

In [34]:
from post_processing.NN.DNNModel import DNNModel, draw_all_stats
import post_processing.NN.utils as utils

DNN = DNNModel(model_config=model_config, modeldir= NOTEBOOKS/'model_custom', log_level=logging.DEBUG)
model_df = DNN.set_model_df_from_total_df(df)
X_train, X_test, Y_train, Y_test, evs_test, sw_train = DNN.Full_Splitting(model_df)
input_layer, normalized_input = DNN.input_preprocessing(X_train)

DNN.build_model(input_layer=input_layer, normalized_input=normalized_input, fixed_random_seed=True)
DNN.train_model(X_train, Y_train, sw_train)
DNN.save_model_info(X_train.columns, Y_train, Y_test)
output_df, model_metrics = DNN.evaluate_and_predict(X_test, Y_test, evs_test)
cm_norm_true, cm_norm_pred, diag_names = draw_all_stats(DNN_type=DNN.type, history=DNN.history, output_df=output_df, modeldir=DNN.modeldir, classes=DNN.classes)

Initializing model: multi_HH_ttbar_tW
HH_bbWW
Total sum of genWeights for HH_bbWW: 137.84710693359375
Total sum of sample_weights for HH_bbWW: 2340784.0
ttbar
Total sum of genWeights for ttbar: 414462528.0
Total sum of sample_weights for ttbar: 18726300.0
tW
Total sum of genWeights for tW: 10632820.0
Total sum of sample_weights for tW: 9363136.0

Preprocessing input ...

Building model ...
Sumary of model compiled

Model: "multi_HH_ttbar_tW"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)  │ (None, 40)        │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ normalization       │ (None, 40)        │          0 │ input[0][0]       │
│ (Normalization)     │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_0 (Dense)     │ (None, 64)        │      2,624 │ normalization[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 64)        │        256 │ layer_0[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_12          │ (None, 64)        │          0 │ batch_normalizat… │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_1 (Dense)     │ (None, 64)        │      4,160 │ dropout_12[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 64)        │        256 │ layer_1[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_13          │ (None, 64)        │          0 │ batch_normalizat… │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ add_2 (Add)         │ (None, 64)        │          0 │ dropout_13[0][0], │
│                     │                   │            │ dropout_12[0][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ layer_2 (Dense)     │ (None, 64)        │      4,160 │ add_2[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 64)        │        256 │ layer_2[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_14          │ (None, 64)        │          0 │ batch_normalizat… │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ output (Dense)      │ (None, 3)         │        195 │ dropout_14[0][0]  │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 11,907 (46.51 KB)

 Trainable params: 11,523 (45.01 KB)

 Non-trainable params: 384 (1.50 KB)

None

Training model ...

Epoch 1/35
 829/1372 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.6984 - auc_pr: 0.6949 - auc_roc: 0.8282 - f1_score_macro: 0.3413 - f1_score_micro: 0.6984 - loss: 16.8983 - precision: 0.7654 - precision_HH: 0.0067 - precision_tW: 0.3301 - precision_ttbar: 0.8665 - recall: 0.4770 - recall_HH: 0.0471 - recall_tW: 0.0799 - recall_ttbar: 0.5481

In [28]:
Y_train

         Class_HH  Class_tW  Class_ttbar
1109633     False     False         True
1016620     False     False         True
945513      False     False         True
712030      False     False         True
1188746     False     False         True
...           ...       ...          ...
1087374     False     False         True
476944      False     False         True
1019360     False     False         True
176099      False      True        False
1987041     False     False         True

[1872627 rows x 3 columns]

In [30]:
DNN.classes

['HH', 'ttbar', 'tW']

In [31]:
def run_custom(DNNObject, compiled_model):
    DNNObject.model = compiled_model
    DNNObject.train_model(X_train, Y_train, sw_train)
    output_df, model_metrics = DNNObject.evaluate_and_predict(X_test, Y_test, evs_test)
    utils.draw_score_distribution(DNNObject.type, output_df, DNNObject.modeldir)

         Class_HH  Class_tW  Class_ttbar
836358      False     False         True
1357097     False     False         True
1313274     False     False         True
1954390     False     False         True
735623      False     False         True
...           ...       ...          ...
128457      False      True        False
2270162     False     False         True
850426      False     False         True
414996      False     False         True
1129348     False     False         True

[468157 rows x 3 columns]